# Generated by Django 3.2.22 on 2024-10-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
